name: billit_now
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc_concurrency: ^0.2.5
  flutter_bloc: ^8.1.6
  go_router: ^14.6.1
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0 #TODO couldn't update version to latest because of env issue
  dio: ^5.7.0
  fpdart: ^1.1.1
  google_sign_in: ^6.2.2
  google_sign_in_android: ^6.1.33
  intl: ^0.19.0 #TODO couldn't update version to latest because of env issue
  shared_preferences: ^2.3.5
  injectable: ^2.5.0
  get_it: ^8.0.2
  hive_flutter: ^1.1.0
  pretty_dio_logger: ^1.4.0
  bloc: ^8.1.2
  chewie: ^1.8.5
  video_player: ^2.9.2
  device_info_plus: ^9.0.2
  package_info_plus: ^8.1.1
  firebase_messaging: ^15.1.6
  flutter_map: ^7.0.2
  url_launcher: ^6.3.1
  loading_animation_widget: ^1.3.0
  lottie: ^3.2.0

  carousel_slider: ^5.0.0
  flutter_multi_formatter: ^2.13.0
  just_audio: ^0.9.42
  country_flags: ^3.0.0
  intl_phone_field: ^3.2.0
  flutter_spinkit: ^5.2.1
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.15
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
#  sign_in_with_apple: ^4.0.0
  flutter_facebook_auth: ^7.1.1
  googleapis: ^13.2.0
  visibility_detector: ^0.4.0+2
  shimmer: ^2.0.0
  skeletonizer: ^1.4.2
  xml: ^6.5.0
  path_drawing: ^1.0.0
  zoomable_interactive_viewer: ^0.0.5
  jwt_decoder: ^2.0.1
  qr_flutter: ^4.1.0
  oktoast: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
  retrofit_generator: '>=8.0.0 <10.0.0'
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  freezed: ^2.5.7

flutter:


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/locales/
    - assets/images/
    - assets/videos/
    - assets/musics/
    - assets/anims/
    - assets/svg/

  fonts:
    - family: SourceSans3
      fonts:
        - asset: fonts/SourceSans3-ExtraLight.ttf
          weight: 200
        - asset: fonts/SourceSans3-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/SourceSans3-Light.ttf
          weight: 300
        - asset: fonts/SourceSans3-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/SourceSans3-Regular.ttf
          weight: 400
        - asset: fonts/SourceSans3-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/SourceSans3-Medium.ttf
          weight: 500
        - asset: fonts/SourceSans3-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/SourceSans3-SemiBold.ttf
          weight: 600
        - asset: fonts/SourceSans3-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/SourceSans3-Bold.ttf
          weight: 700
        - asset: fonts/SourceSans3-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/SourceSans3-ExtraBold.ttf
          weight: 800
        - asset: fonts/SourceSans3-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/SourceSans3-Black.ttf
          weight: 900
        - asset: fonts/SourceSans3-BlackItalic.ttf
          weight: 900
          style: italic
    - family: SourceSerif4
      fonts:
        - asset: fonts/SourceSerif4-ExtraLight.ttf
          weight: 200
        - asset: fonts/SourceSerif4-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/SourceSerif4-Light.ttf
          weight: 300
        - asset: fonts/SourceSerif4-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/SourceSerif4-Regular.ttf
          weight: 400
        - asset: fonts/SourceSerif4-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/SourceSerif4-Medium.ttf
          weight: 500
        - asset: fonts/SourceSerif4-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/SourceSerif4-SemiBold.ttf
          weight: 600
        - asset: fonts/SourceSerif4-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/SourceSerif4-Bold.ttf
          weight: 700
        - asset: fonts/SourceSerif4-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/SourceSerif4-ExtraBold.ttf
          weight: 800
        - asset: fonts/SourceSerif4-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/SourceSerif4-Black.ttf
          weight: 900
        - asset: fonts/SourceSerif4-BlackItalic.ttf
          weight: 900
          style: italic
    - family: yekan_bakh
      fonts:
        - asset: fonts/YekanBakh.ttf