// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYUV6T3SWzU4t0pqIUxLl33O7d-y8kf_g',
    appId: '1:1087817668813:web:d7f77ca8a43d82c75a7184',
    messagingSenderId: '1087817668813',
    projectId: 'billit-now',
    authDomain: 'billit-now.firebaseapp.com',
    storageBucket: 'billit-now.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtCnD3auOAKbyoq6yFuwTHkBptYJK4Blk',
    appId: '1:1087817668813:android:e7993f5cf7bde1935a7184',
    messagingSenderId: '1087817668813',
    projectId: 'billit-now',
    storageBucket: 'billit-now.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSh_DAPGI5ZtLlDd3mEU-SVZk2QpL5pVQ',
    appId: '1:1087817668813:ios:b45ac6f36ac0dc815a7184',
    messagingSenderId: '1087817668813',
    projectId: 'billit-now',
    storageBucket: 'billit-now.appspot.com',
    iosBundleId: 'com.example.billitNow',
  );
}
